FROM --platform=linux/amd64 ubuntu:16.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake git python
ENV CC=gcc
ENV CXX=g++

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8

FROM ubuntu:16.04 as package
COPY --from=builder /repo/build/DCMTK-build/bin/dcm2xml /
